#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Migrating current django app schema to the PostgreSQL database"
python manage.py makemigrations --noinput

echo "Applying migrations"
python manage.py migrate

echo "Create superuser"
echo "from healthcare_gov_swe6160.users.models import User; User.objects.filter(email='$DJANGO_ADMIN_EMAIL').delete(); User.objects.create_superuser('$DJANGO_ADMIN_USER', '$DJANGO_ADMIN_EMAIL', '$DJANGO_ADMIN_PASSWORD')" | python manage.py shell

echo "Starting local development server"
exec python manage.py runserver_plus 0.0.0.0:8000
